spring:
    redis:
        host: localhost
        port: 6379
        lettuce:
            pool:
                max-active: 10
                time-between-eviction-runs: PT60S
                max-idle: 10
    jta:
        atomikos:
            properties:
                max-actives: 100
                max-timeout: 10000
                default-jta-timeout: 5000
